<a href="https://colab.research.google.com/github/Ravneet-kaur1102/DataScienceTraining/blob/main/Day_3_5_NumPy_Pandas_Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mount Google Drive
Run this code cell to mount your Google Drive. This gives you a permanent place to save your datasets and notebooks before pushing them to GitHub.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


NumPy Operations (ndarray, reshaping, broadcasting, statistical ops)

In [ ]:
import numpy as np

print("--- 1. Creating an ndarray ---")
# Create a 1D array of 12 elements (representing monthly sales coefficients)
sales_coefficients = np.array([1.1, 0.9, 1.3, 0.8, 1.0, 1.2, 1.5, 0.7, 1.1, 1.4, 0.9, 1.2])
print("Original Array:", sales_coefficients)

print("\n--- 2. Reshaping ---")
# Reshape to a 4x3 matrix (representing 4 quarters, 3 months each)
quarterly_matrix = sales_coefficients.reshape(4, 3)
print("Reshaped Matrix (4 Quarters x 3 Months):\n", quarterly_matrix)

print("\n--- 3. Broadcasting ---")
# Broadicast a base value update: Multiply the entire matrix by a base target factor of 1000
projected_sales = quarterly_matrix * 1000
print("Projected Sales (After Broadcasting):\n", projected_sales)

print("\n--- 4. Statistical Operations ---")
print(f"Total Projected Sales: {projected_sales.sum()}")
print(f"Average Sales per Quarter: {projected_sales.mean(axis=1)}")
print(f"Max Sales Coefficient: {sales_coefficients.max()}")

--- 1. Creating an ndarray ---
Original Array: [1.1 0.9 1.3 0.8 1.  1.2 1.5 0.7 1.1 1.4 0.9 1.2]

--- 2. Reshaping ---
Reshaped Matrix (4 Quarters x 3 Months):
 [[1.1 0.9 1.3]
 [0.8 1.  1.2]
 [1.5 0.7 1.1]
 [1.4 0.9 1.2]]

--- 3. Broadcasting ---
Projected Sales (After Broadcasting):
 [[1100.  900. 1300.]
 [ 800. 1000. 1200.]
 [1500.  700. 1100.]
 [1400.  900. 1200.]]

--- 4. Statistical Operations ---
Total Projected Sales: 13100.0
Average Sales per Quarter: [1100.         1000.         1100.         1166.66666667]
Max Sales Coefficient: 1.5


Create a Dummy "Sales Dataset" CSV
Run this cell to generate a mock dataset so you can practice Pandas CSV Input/Output (I/O).

In [ ]:
import pandas as pd

# Creating a mock dictionary
raw_data = {
    'Transaction_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Region': ['North', 'East', 'West', 'South', 'North', 'West', 'East', 'South', 'North', 'West'],
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Laptop', 'Mobile', None, 'Tablet', 'Laptop', 'Mobile', 'Tablet'],
    'Units_Sold': [5, 12, np.nan, 8, 15, 7, 9, np.nan, 14, 11],
    'Unit_Price': [1200, 800, 400, 1200, 800, 450, 400, 1200, 800, 400]
}

# Convert to DataFrame
df_mock = pd.DataFrame(raw_data)

# Export to CSV (CSV I/O)
df_mock.to_csv('sales_dataset.csv', index=False)
print("Mock 'sales_dataset.csv' successfully created and saved locally!")

Mock 'sales_dataset.csv' successfully created and saved locally!


Pandas Core Essentials (info(), describe(), Missing Data)

In [ ]:
# Read the CSV back into Pandas
df = pd.read_csv('sales_dataset.csv')

print("--- 1. Checking Data Integrity using info() ---")
print(df.info())

print("\n--- 2. Summary Statistics using describe() ---")
print(df.describe())

print("\n--- 3. Handling Missing Data ---")
print("Missing items check:\n", df.isnull().sum())

# Handling the missing values
df['Product'] = df['Product'].fillna('Unknown') # fillna for categorical
df['Units_Sold'] = df['Units_Sold'].fillna(df['Units_Sold'].median()) # fillna with median for numeric

print("\nCleaned Dataframe (No Missing Values):")
print(df)

--- 1. Checking Data Integrity using info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Transaction_ID  10 non-null     int64  
 1   Region          10 non-null     object 
 2   Product         9 non-null      object 
 3   Units_Sold      8 non-null      float64
 4   Unit_Price      10 non-null     int64  
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes
None

--- 2. Summary Statistics using describe() ---
       Transaction_ID  Units_Sold   Unit_Price
count        10.00000    8.000000    10.000000
mean        105.50000   10.125000   765.000000
std           3.02765    3.482097   344.842959
min         101.00000    5.000000   400.000000
25%         103.25000    7.750000   412.500000
50%         105.50000   10.000000   800.000000
75%         107.75000   12.500000  1100.000000
max         110.00000   15.000000  1200.

Advanced Queries (Filtering, loc/iloc, Boolean Indexing)

In [ ]:
print("--- 1. Boolean Indexing (Units Sold > 10) ---")
high_volume = df[df['Units_Sold'] > 10]
print(high_volume)

print("\n--- 2. Filtering by Multiple Conditions (Region == North & Price == 800) ---")
filtered_df = df[(df['Region'] == 'North') & (df['Unit_Price'] == 800)]
print(filtered_df)

print("\n--- 3. Using .loc (Label-based indexing: fetch specific rows and columns) ---")
# Get rows index 0 to 3, only 'Product' and 'Unit_Price' columns
print(df.loc[0:3, ['Product', 'Unit_Price']])

print("\n--- 4. Using .iloc (Integer-position based indexing) ---")
# Get the first 2 rows and the first 3 columns
print(df.iloc[0:2, 0:3])

--- 1. Boolean Indexing (Units Sold > 10) ---
   Transaction_ID Region Product  Units_Sold  Unit_Price
1             102   East  Mobile        12.0         800
4             105  North  Mobile        15.0         800
8             109  North  Mobile        14.0         800
9             110   West  Tablet        11.0         400

--- 2. Filtering by Multiple Conditions (Region == North & Price == 800) ---
   Transaction_ID Region Product  Units_Sold  Unit_Price
4             105  North  Mobile        15.0         800
8             109  North  Mobile        14.0         800

--- 3. Using .loc (Label-based indexing: fetch specific rows and columns) ---
  Product  Unit_Price
0  Laptop        1200
1  Mobile         800
2  Tablet         400
3  Laptop        1200

--- 4. Using .iloc (Integer-position based indexing) ---
   Transaction_ID Region Product
0             101  North  Laptop
1             102   East  Mobile


Answering Business Questions (groupby, agg, merge, sort_values)
Here are core calculations designed to answer specific business performance questions using your dataset manipulation functions.

In [ ]:
# Feature Engineering a revenue column for analytics
df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']

print("--- Question 1: What is the total revenue generated by each Region? ---")
region_performance = df.groupby('Region')['Total_Revenue'].sum().reset_index()
print(region_performance.sort_values(by='Total_Revenue', ascending=False))

print("\n--- Question 2: What are the total units sold and average price per product? ---")
product_stats = df.groupby('Product').agg(
    Total_Units=('Units_Sold', 'sum'),
    Avg_Price=('Unit_Price', 'mean')
).reset_index()
print(product_stats)

print("\n--- Question 3: How to combine performance metrics with region managers? (Merge Demo) ---")
# Creating a secondary dataframe to practice merge()
managers_data = {
    'Region': ['North', 'East', 'West', 'South'],
    'Manager': ['Alice', 'Bob', 'Charlie', 'Diana']
}
df_managers = pd.DataFrame(managers_data)

# Merging both dataframes together
final_business_report = pd.merge(df, df_managers, on='Region', how='inner')
print(final_business_report[['Transaction_ID', 'Region', 'Manager', 'Product', 'Total_Revenue']])

--- Question 1: What is the total revenue generated by each Region? ---
  Region  Total_Revenue
1  North        29200.0
2  South        21600.0
0   East        13200.0
3   West        11550.0

--- Question 2: What are the total units sold and average price per product? ---
   Product  Total_Units  Avg_Price
0   Laptop         23.0     1200.0
1   Mobile         41.0      800.0
2   Tablet         30.0      400.0
3  Unknown          7.0      450.0

--- Question 3: How to combine performance metrics with region managers? (Merge Demo) ---
   Transaction_ID Region  Manager  Product  Total_Revenue
0             101  North    Alice   Laptop         6000.0
1             102   East      Bob   Mobile         9600.0
2             103   West  Charlie   Tablet         4000.0
3             104  South    Diana   Laptop         9600.0
4             105  North    Alice   Mobile        12000.0
5             106   West  Charlie  Unknown         3150.0
6             107   East      Bob   Tablet         360